version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      # Ignore all patch releases as we can manually
      # upgrade if we run into a bug and need a fix.
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
