#!/bin/sh -e

export PREFIX="venv/bin/"

set -x

if [ -d 'venv' ] ; then
  echo "Python virtual env already exists."
  ${PREFIX}python --version
else
  python -m venv venv
fi

${PREFIX}python -m pip install -U pip build wheel
${PREFIX}python -m pip install -r dev-requirements.txt

set +x
