#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="kiss_headers tests"

set -x
${PREFIX}black --target-version=py37 $SOURCE_FILES
${PREFIX}isort --project=kiss_headers $SOURCE_FILES
